spring:
  application:
    name: learner-product-api
  profiles:
    active:
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: ****
    #    url
    password: root
    url: jdbc:mysql://34.171.47.197:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    #    password: **** JAVA_OPTS=-Dspring.profile="test"
    #    url
    password: Gcp@2023 # 100% ,ciphers ===>  devs will encrypt this usig spring
    url: jdbc:mysql://35.225.248.237:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.247.48.119:30279/eureka/
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    #    password: **** JAVA_OPTS=-Dspring.profile="test"
    #    url
    password: Gcp@2023 # 100% ,ciphers ===>  devs will encrypt this usig spring
    url: jdbc:mysql://35.225.248.237:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.247.48.119:32481/eureka/
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    #    password: **** JAVA_OPTS=-Dspring.profile="test"
    #    url
    password: Gcp@2023 # 100% ,ciphers ===>  devs will encrypt this usig spring
    url: jdbc:mysql://35.225.248.237:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.247.48.119:30536/eureka/
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    #    password: **** JAVA_OPTS=-Dspring.profile="test"
    #    url
    password: Gcp@2023 # 100% ,ciphers ===>  devs will encrypt this usig spring
    url: jdbc:mysql://35.225.248.237:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.247.48.119:31331/eureka/
---
